version: '2.0'

services:
#  zipkin:
#    image: "openzipkin/zipkin"
#    hostname: zipkin
#    ports:
#      - "9411:9411"
  company-bulletin-board:
    image: "servicecomb/service-center"
    hostname: service-center
    ports:
      - "30100:30100"

  company-worker:
    image: "worker:0.0.1-SNAPSHOT"
    hostname: worker
    links:
      - "company-bulletin-board:sc.servicecomb.io"
#      - "zipkin:zipkin.io"
    environment:
      - ARTIFACT_ID=worker
    ports:
      - "7070:7070"
      - "8080:8080"

  company-doorman:
    image: "doorman:0.0.1-SNAPSHOT"
    hostname: doorman
    links:
      - "company-bulletin-board:sc.servicecomb.io"
#      - "zipkin:zipkin.io"
    environment:
      - ARTIFACT_ID=doorman
    ports:
      - "8081:8080"

  company-beekeeper:
    image: "beekeeper:0.0.1-SNAPSHOT"
    hostname: beekeeper
    links:
      - "company-bulletin-board:sc.servicecomb.io"
#      - "zipkin:zipkin.io"
      - "company-worker"
    environment:
      - ARTIFACT_ID=beekeeper
    ports:
      - "8082:8090"

  company-manager:
    image: "manager:0.0.1-SNAPSHOT"
    hostname: manager
    links:
      - "company-bulletin-board:sc.servicecomb.io"
#      - "zipkin:zipkin.io"
    environment:
      - JAVA_OPTS=-Dserver.port=8080 #-Dlogging.level.root=DEBUG
      - ARTIFACT_ID=manager
    ports:
      - "8083:8080"
